---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ21N20"
  stages:
    Release:
      cfCredentialsId: "cfdeploy"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Acceptance:
    cloudFoundryDeploy: false
    npmExecuteEndToEndTests: false
  Malware Scan:
    malwareExecuteScan: false
  Release:
    tmsExport: false
    tmsUpload: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "5602d5e4trial"
    cfSpace: "dev"
    deployType: "standard"
    cloudFoundryDeploy: true
  Additional Unit Tests:
    npmExecuteScripts: true
  Compliance:
    sonarExecuteScan: true
steps:
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "testaccount"
    credentialsId: "ctms"
  npmExecuteScripts:
    runScripts:
    - "test"
  sonarExecuteScan:
    mode: "SonarCloud"
    serverUrl: "https://sonarcloud.io"
    organization: "alrikx"
    projectKey: "alrikx_incident-management"
    sonarTokenCredentialsId: "sonarcloudcredentials"
  artifactPrepareVersion:
    versioningType: "cloud_noTag"