name: CI Pipeline for Main
run-name: ${{ github.actor }} started CI 🚀
on:
  workflow_dispatch:
  push:
    branches: [ main-github-actions ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      #- name: List files in the repository
      #  run: ls ${{ github.workspace }}

      - name: Setup Node 20.12.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.0
      
      #- name: Building
      #  run: npm ci

      #- name: Executing unit tests
      #  run: npm test

      #- name: SonarCloud Scan
      #  uses: SonarSource/sonarcloud-github-action@v3.1.0
      #  env:
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Make the mtar build and deploy script executable
        run: chmod +x ./.github/workflows/scripts/btp_deploy.sh
        
      - name: Run mtar build and deploy
        env:
          cf_user: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_api_url: ${{vars.CF_API_URL}}
          cf_org: ${{vars.CF_ORG}}
          cf_space: ${{vars.CF_SPACE}}
        run: ./.github/workflows/scripts/btp_deploy.sh

      - id: ctms_upload
        name: Handover to cTMS
        uses: SAP/project-piper-action@main
        with:
          step-name: tmsUpload
          flags: --nodeName testaccount --mtaPath ./mta_archives/app.mtar --serviceKey ${{ secrets.CTMS }} --customDescription 123 --namedUser ${{ github.actor }}
          #${{ github.event.head_commit.message }}
      
      - uses: neonidian/teams-notify-build-status@v3
        with:
          webhookUrl: ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL_1 }}
          title: Ended Pipeline                                      # Specify a title header
          titleBackgroundColor: ${{ steps.ctms_upload.outcome }}    # Specify title background color. 'unitTest' is the ID of a step
          status: ${{ steps.ctms_upload.outcome }}                  # Specify what should be displayed in the status label
          message: >-
            This is a test
        env:                                                     # Enable actor labels and buttons using environment variables
          SHOULD_DISPLAY_ACTOR_LABEL: true
          SHOULD_DISPLAY_VIEW_RUN_BUTTON: true
          SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: true