name: PR Voting
run-name: ${{ github.actor }} send a pull Request
on:
  pull_request:
    types: [opened, reopened]
    branches:  
      - main-github-actions

#needed for the Test Report step to update the PR
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  pull-request-voting:
    #permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    #- name: List files in the repository
    #  run: ls ${{ github.workspace }}

    - name: Setup Node 20.12.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.12.0
    
    - name: Building
      run: npm ci

    - name: Executing Unit tests
      run: npm test

    - name: Upload Test Report to PR
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: cloudcitransfer/junit/jest-*.xml    # Path to test results
        reporter: jest-junit        # Format of test results

    #unfixed if dependabot runs the PR check, it cant access sonar token
    # https://github.com/dependabot/dependabot-core/issues/3253
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v3.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.pullrequest.key=${{ github.event.number }}
